name: Check System Files List

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:    
  build-win:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: ls C:\Users\
    - run: ls C:\Users\installer
    - run: ls C:\Users\RMAGEN~1
    - run: ls C:\Users\runneradmin
    
